### ISSUE TITLE
Current Status?

### ISSUE THREAD

**Issue by proffalken** [mojtabaakbari221b/django_otlp_log_exporter#2]
Hello,

I'm assuming this module is currently in maintenance mode (or even unmaintained?)

I want to add `HTTP/PROTOBUF` support, but I'm wondering whether you're accepted PR's for this repo?

**Comment by mojtabaakbari221b** [comment]
I wrote this project in the company where I work, but I thought it would be useful to share it, but I don't have time to develop it further at the moment.
I will be happy to develop it by you and if your development is good, I will definitely merge it
